/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { VivoApiV1SaludGet$Params as VivoApiV1SaludGet$Params } from './fn/salud/vivo-api-v-1-salud-get';
export { vivoApiV1SaludGet as vivoApiV1SaludGet } from './fn/salud/vivo-api-v-1-salud-get';
export type { ListoApiV1SaludListoGet$Params as ListoApiV1SaludListoGet$Params } from './fn/salud/listo-api-v-1-salud-listo-get';
export { listoApiV1SaludListoGet as listoApiV1SaludListoGet } from './fn/salud/listo-api-v-1-salud-listo-get';
