/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { provideApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { Api } from './api';

export type { PreparacionOut } from './models/preparacion-out';
export type { Problema } from './models/problema';
export type { SaludOut } from './models/salud-out';

export type { VivoApiV1SaludGet$Params as VivoApiV1SaludGet$Params } from './fn/salud/vivo-api-v-1-salud-get';
export { vivoApiV1SaludGet as vivoApiV1SaludGet } from './fn/salud/vivo-api-v-1-salud-get';
export type { ListoApiV1SaludListoGet$Params as ListoApiV1SaludListoGet$Params } from './fn/salud/listo-api-v-1-salud-listo-get';
export { listoApiV1SaludListoGet as listoApiV1SaludListoGet } from './fn/salud/listo-api-v-1-salud-listo-get';
