/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { PreparacionOut } from './models/preparacion-out';
export type { Problema } from './models/problema';
export type { SaludOut } from './models/salud-out';
