/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Readiness: todas las dependencias están disponibles.
 */
export interface PreparacionOut {
  comprobaciones: {
[key: string]: 'ok';
};
  estado: 'listo';
}
