/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalle de problema; admite extensiones como `errores` o `comprobaciones`.
 */
export interface Problema {
  detail?: (string | null);

  /**
   * `urn:uuid:<correlation_id>` de la petición.
   */
  instance: string;
  status: number;
  title: string;

  /**
   * Código de error de docs/04-api.md §12.
   */
  type: string;

  [key: string]: any;
}
