/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PreparacionOut } from '../../models/preparacion-out';

export interface ListoApiV1SaludListoGet$Params {
}

export function listoApiV1SaludListoGet(http: HttpClient, rootUrl: string, params?: ListoApiV1SaludListoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PreparacionOut>> {
  const rb = new RequestBuilder(rootUrl, listoApiV1SaludListoGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PreparacionOut>;
    })
  );
}

listoApiV1SaludListoGet.PATH = '/api/v1/salud/listo';
