/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaludOut } from '../../models/salud-out';

export interface VivoApiV1SaludGet$Params {
}

export function vivoApiV1SaludGet(http: HttpClient, rootUrl: string, params?: VivoApiV1SaludGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SaludOut>> {
  const rb = new RequestBuilder(rootUrl, vivoApiV1SaludGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SaludOut>;
    })
  );
}

vivoApiV1SaludGet.PATH = '/api/v1/salud';
